### ISSUE TITLE
How do you build the app?

### ISSUE THREAD

**Issue by rvilarl** [jaredjj3/vexml#3]
@jaredjj3 quite simple question, how do you build and run this repo? I am used to `npm run` or `grunt`. I used `tsc` and I got the .js but running `index.html` did not work :(

**Comment by jaredjj3** [comment]
I've been using the [Stackblitz link](https://stackblitz.com/edit/typescript-fbkn55), which sets up the dev server with hot reloading.

However, I added a mechanism to build the project and updated the README for instructions on how to build/run locally. Pull `master` and give that a try. Feel free to reopen if you still can't build it.
