### ISSUE TITLE
Move project under @stringsync org?

### ISSUE THREAD

**Issue by jaredjj3** [jaredjj3/vexml#6]
@rvilarl, I would like to move the project under the [stringsync](https://github.com/stringsync) org. I'll make sure you retain your ability as a repo owner. Are you ok with this?

**Comment by rvilarl** [comment]
What kind of organization is stringsync? I do not mind the repository but I would like to stay in the licence. I guess you want to chnage the copyright to stringsync

**Comment by jaredjj3** [comment]
>What kind of organization is stringsync?

It's where I want to publish all the free tools that I'm using in stringsync.com

I'm good with keeping the license as MIT. I'll leave the copyright as is. Thanks!
